[package]
name = "buck2_server_commands"
version = "0.1.0"
edition = "2021"
description = "Implementation of several Buck commands"

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
indent_write = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
os_str_bytes = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

dice = { path = "../dice/dice" }
dupe = { workspace = true }
gazebo = { workspace = true }
allocative = { workspace = true }
starlark_map = { workspace = true }

buck2_build_api = { path = "../buck2_build_api" }
buck2_common = { path = "../buck2_common" }
buck2_core = { path = "../app/buck2_core" }
buck2_data = { path = "../buck2_data" }
buck2_events = { path = "../buck2_events" }
buck2_execute = { path = "../buck2_execute" }
buck2_interpreter_for_build = { path = "../app/buck2_interpreter_for_build" }
buck2_node = { path = "../buck2_node" }
buck2_query = { path = "../buck2_query" }
buck2_server_ctx = { path = "../buck2_server_ctx" }
cli_proto = { path = "../cli_proto" }
install_proto = { path = "../install_proto" }
