[package]
name = "buck2_interpreter_tests"
version = "0.1.0"
edition = "2021"
description = "Tests for buck2_intepreter"

[dev-dependencies]
indoc = { workspace = true }

buck2_interpreter_for_build = { workspace = true }
