[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]

gazebo = {version = "0.8.1", features = ["str_pattern_extensions"]}
fbinit = "0.1"
sorted_vector_map = "0.1"
watchman_client = "0.8.0"

unicode-segmentation = "1.7"
annotate-snippets = { version = "0.9.0", features = ["color"] }
anyhow = "1.0.65"
anymap = "0.12.1"
argfile = "0.1.0"
assert_matches = "1.5"
async-compression = { version = "0.3.8", features = ["tokio", "gzip", "zstd"] }
async-condvar-fair = { version = "0.2.2", features = ["parking_lot_0_11"] }
async-recursion = "1.0"
async-stream = "0.3.2"
async-trait = "0.1.24"
backtrace = "0.3.51"
base64 = "0.13.0"
bincode = "1.3.3"
blake3 = "0.3.7"
bumpalo = "=3.8.0"
byteorder = "1.4.3"
bytes = "1.0"
bytesize = "1.1.0"
chrono = "=0.4.19"  # Avoid a dependency iana-time-zone, which requires a fixup
clap-4 = { package = "clap", version = "4.0.7", features = ["derive", "env"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
compact_str = "0.6"
constant_time_eq = "0.2.4"
convert_case = "0.4.0"
criterion = { version = "0.3.4", features = ["async", "async_tokio", "html_reports"] }
crossbeam-channel = "0.5"
crossbeam-epoch = "0.9.7"
crossterm = "0.23"
ctor = "0.1.26"
dashmap = "4.0.2"
debugserver-types = "0.5.0"
derivative = "2.1.1"
derive_more = "0.99.3"
dirs = "3.0.1"
dunce = "1.0.3"
either = "1.8"
enum-iterator = "0.5.0"
enum-map = "0.6.4"
env_logger = "0.9.2"
erased-serde = "0.3.20"
faccess = "0.2.3"
fancy-regex = "0.10.0"
flate2 = "1.0.22"
fnv = "1.0.7"
fs2 = "0.4.3"
futures = { version = "0.3.24", features = ["async-await", "compat"] }
futures-intrusive = "0.4"
glob = "0.3.0"
globset = "0.4.7"
hashbrown = { version = "0.12.3", features = ["raw"] }
hex = "0.4.3"
hostname = "0.3.1"
http = "0.2"
httparse = "1.7.1"
humantime = "2.0.1"
indent_write = "2.2.0"
indexmap = { version = "1.9.1", features = ["serde-1"] }
indoc = "1.0.3"
inferno = "0.11.11"
internment = "0.4.0"
inventory = "0.1.10"
itertools = "0.10.3"
jemalloc-ctl = "0.3.3"
jemallocator = { version = "0.3.2", features = ["profiling"] }
lalrpop = "0.19.7"
lalrpop-util = "0.19.7"
libc = "0.2.132"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
log = "0.4"
logos = "0.12"
lsp-server = "0.5"
lsp-types = "0.93.0"
maplit = "1.0.2"
memchr = "2.4.1"
memmap = "0.7.0"
memoffset = "0.6.4"
multimap = "0.8.3"
nix = "0.22"
nom = "6.1.2"
notify = "=5.0.0-pre.16"
num_cpus = "1.11"
num-bigint = "0.4.3"
num-traits = "0.2"
object = "0.25.3"
once_cell = "1.8"
os_str_bytes = "6.0"
owning_ref = "0.4.1"
parking_lot = { version = "0.11.2", features = ["send_guard"] }
paste = "1.0"
pin-project = "0.4.29"
plist = "0.5"
pretty_assertions = "0.6"
proc-macro2 = "1.0"
prost = "0.11.6"
prost-build = "0.11.6"
prost-derive = "0.11.6"
prost-types = "0.11.6"
quote = "1.0.3"
rand = { version = "0.8.4", features = ["small_rng"] }
ref-cast = "1.0.0"
regex = "1.5.4"
relative-path = { version = "1.7.0", features = ["serde"] }
reqwest = { version = "0.11.4", features = ["stream"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
rustyline = "9.1"
sequence_trie = "0.3.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
sha-1 = "0.10"
sha2 = "0.10"
shlex = "1.1"
siphasher = "0.3.5"
slog = "2.7.0"
smallvec = "1.7"
static_assertions = "1.1.0"
strsim = "0.10.0"
structopt = "0.3.23"
syn = { version = "1.0.27", features = ["extra-traits", "full"] }
sync_wrapper = "0.1.0"
sys-info = "0.9.1"
sysinfo = "0.26.8"
take_mut = "0.2.2"
tempfile = "3.1.0"
termimad = "0.20.1"
termios = "0.3"
termwiz = "0.18"
test-case = "1.2.0"
textwrap = { version = "0.15", default-features = false }  # Don't want to pull in unicode-linebreak as it needs a fixup
thiserror = "1.0.36"
threadpool = "1.8.1"
tokio = { version = "1.5", features = ["full"] }
tokio-stream = { version = "0.1.4", features = ["fs", "io-util", "net", "sync", "time"] }
tokio-util = { version = "0.7.1", features = ["full"] }
toml = "0.5.8"
tonic = "0.8.3"
tonic-build = { version = "0.8.4", features = ["prost", "cleanup-markdown"] }
tower = "0.4"
tower-layer = "0.3.1"
tower-service = "0.3.2"
tracing = "0.1.22"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
trybuild = "1.0.56"
twox-hash = "1.6.1"
uuid = { version = "0.8", features = ["v4"] }
walkdir = "2.3.2"
which = "4.3.0"
winapi = { version = "0.3", features = ["everything"] }
xattr = "0.2.2"
zip = "0.5"
zstd = "=0.11.1"

[patch.crates-io]
# For https://github.com/tokio-rs/prost/pull/802
prost = { git = "https://github.com/krallin/prost.git", rev = "90b7e204c66f6baed0b1426ce456fb70d16b1cdb", version = "0.11.6"}
prost-build = { git = "https://github.com/krallin/prost.git", rev = "90b7e204c66f6baed0b1426ce456fb70d16b1cdb", version = "0.11.6"}
prost-types = { git = "https://github.com/krallin/prost.git", rev = "90b7e204c66f6baed0b1426ce456fb70d16b1cdb", version = "0.11.6"}
prost-derive = { git = "https://github.com/krallin/prost.git", rev = "90b7e204c66f6baed0b1426ce456fb70d16b1cdb", version = "0.11.6"}
# For https://github.com/hyperium/tonic/pull/1252
tonic = { git = "https://github.com/krallin/tonic.git", rev = "c67fc25b636b48b90c83dfc8dd1f89c00b84846d", version = "0.8.3" }
tonic-build = { git = "https://github.com/krallin/tonic.git", rev = "c67fc25b636b48b90c83dfc8dd1f89c00b84846d", version = "0.8.4" }
