[package]
name = "buck2_test"
version = "0.1.0"
edition = "2021"
description = "Buck V2 test runner"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
libc = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

dice = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
host_sharing = { workspace = true }
more_futures = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_execute_impl = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_downward_api = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_test_api = { workspace = true }
buck2_grpc = { workspace = true }
buck2_util = { workspace = true }
