[package]
name = "fuzzy_dice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.24"
clap = { version = "3.1.18", features = ["derive"] }
crossbeam = "0.8"
derive_more = "0.99.3"
derivative = "2.1.1"
futures = "0.3"
itertools = "0.10.3"
parking_lot = { version = "0.11.2", features = ["send_guard"] }
quickcheck = "1.0"
quickcheck_async = "0.1.1"
ref-cast = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
thiserror = "1.0.36"
tokio = { version = "1.5", features = ["full"]}
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.2", features = ["v4"] }

dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
allocative = { workspace = true }

dice = { path = "../dice" }

[dev-dependencies]
# Newer cast pull in semver 1.0, which fails with
# https://github.com/dtolnay/semver/issues/251
futures = "0.3"
anyhow = "1.0.65"

[features]
# @oss-disable: default = ["gazebo_lint"]
