[package]
name = "buck2_starlark"
version = "0.1.0"
edition = "2021"
description = "`buck2 starlark` command implementation, both client and server"

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
dupe = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starlark = { workspace = true }
thiserror = { workspace = true }

buck2_client_ctx = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_server_ctx = { workspace = true }
