[package]
name = "remote_execution"
version = "0.1.0"
edition = "2021"
description = "A library providing remote execution using gRPC"

[dependencies]
anyhow = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
prost-types = { workspace = true }
prost = { workspace = true }
regex = { workspace = true }
slog = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }

gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../../gazebo_lint/gazebo_lint"

buck2_core = { workspace = true }
re_grpc_proto = { path = "../re_grpc_proto" }

[dev-dependencies]
tempfile = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
