[package]
name = "buck2_test_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }

buck2_grpc = { workspace = true }
buck2_test_api = { workspace = true }
