[build]
# `cargo_internal_build` is set for cargo builds inside Meta.
# The flag enables features not available in opensource version,
# in particular, dependencies on libraries not available in open source.
# @oss-disable: rustflags = ["--cfg", "cargo_internal_build"]
