[package]
description = "common utitilies of buck2 profile"
edition = "2021"
name = "buck2_profile"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
inferno = { workspace = true }

starlark = { workspace = true }

buck2_core = { workspace = true }
buck2_interpreter = { workspace = true }
cli_proto = { path = "../../cli_proto" }
