[package]
name = "buck2_build_api"
version = "0.1.0"
edition = "2021"
description = "Build related interpreter defs, coercion logic, some build rule impelementations, and handing actions off to DICE for caching and execution. A large chunk of the 'build' part of BuckV2"

[dependencies]
dashmap = { workspace = true }
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
derive_more = { workspace = true }
derivative = { workspace = true }
hashbrown = { workspace = true }
once_cell = { workspace = true }
indoc = { workspace = true }
inventory = { workspace = true }
fancy-regex = { workspace = true }
futures = { workspace = true }
internment = { workspace = true }
itertools = { workspace = true }
owning_ref = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ref-cast = { workspace = true }
shlex = { workspace = true }
static_assertions = { workspace = true }
structopt = { workspace = true }
take_mut = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
either = { workspace = true }
reqwest = { workspace = true }
sha-1 = { workspace = true }
hex = { workspace = true }
smallvec = { workspace = true }
assert_matches = { workspace = true }
crossbeam-epoch = { workspace = true }
http = { workspace = true }
parking_lot = { workspace = true }
fnv = { workspace = true }

allocative = { workspace = true }
dice = { path = "../../dice/dice" }
fbinit = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
host_sharing = { workspace = true }
more_futures = { workspace = true }
remote_execution = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_build_api_derive = { workspace = true }
buck2_build_info = { workspace = true }
buck2_core = { workspace = true }
buck2_common = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_test_api = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
