# Buildscript sets TARGET in environment
buildscript = []

[platform_fixup.'cfg(aarch64-unknown-linux-gnu)']
env = { TARGET = "aarch64-unknown-linux-gnu" }
buildscript = []

[platform_fixup.'cfg(x86_64-unknown-linux-gnu)']
env = { TARGET = "x86_64-unknown-linux-gnu" }
buildscript = []

[platform_fixup.'cfg(aarch64-apple-darwin)']
env = { TARGET = "aarch64-apple-darwin" }
buildscript = []

[platform_fixup.'cfg(x86_64-apple-darwin)']
env = { TARGET = "x86_64-apple-darwin" }
buildscript = []

[platform_fixup.'cfg(x86_64-pc-windows-msvc)']
env = { TARGET = "x86_64-pc-windows-msvc" }
buildscript = []
