[package]
authors = ["Facebook"]
description = "Proc macros for Buck's buck_query crate"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "buck2_query_derive"
version = "0.4.1"

[lib]
proc-macro = true

[dependencies]
itertools = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
textwrap = { workspace = true }

gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"

[features]
# @oss-disable: default = ["gazebo_lint"]
